name: smart_utility_toolkit
description: "A Simple Smart Utility Toolkit App"

environment:
  sdk: ^3.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation
  go_router: ^13.0.0
  
  # State management 
  provider: ^6.1.2
  
  # HTTP for currency API
  http: ^1.2.1
  
  # Icons
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
